<?php

// This file is generated by Composer
require_once 'vendor/autoload.php';

$stat = prstat();
krsort($stat);
echo '<table border="1">';
echo "<tr><th>Week</th><th>Opened</th><th>Accepted</th><th>Rejected</th>";
foreach ($stat as $week => $weekStat) {
    echo "<tr><td>" . $week . "</td>";
    echo "<td>";
    if (isset($weekStat['opened'])) {
        echo count($weekStat['opened']);
    } else {
        echo 0;
    }

    echo "</td><td>";
    if (array_key_exists('accepted', $weekStat)) {
        echo count($weekStat['accepted']);
    } else {
        echo 0;
    }
    echo  "</td><td>";
    if (isset($weekStat['rejected'])) {
        echo count($weekStat['rejected']);
    } else {
        echo 0;
    }
    echo "</td></tr>";
}
echo "</table>";

function prstat() {

    $esAdapter = new \Vrann\Adapter\ElasticSearch();

    //weeks
    //$dim = 'W';
    //months
    $dim = 'm';

    $esAdapter = new \Vrann\Adapter\ElasticSearch();
    $prs = $esAdapter->get();
    $issues = [];
    foreach ($prs as $prData) {
        $pr = $prData['_source'];

        $matches = [];
        preg_match('/.*(\#\d+)/', $pr['title'], $matches);
        if (count($matches) > 0) {
            $issues[] = $matches[1];
        }
        $matches = [];
        preg_match('/.*(\#\d+)/', $pr['body'], $matches);
        if (count($matches) > 0) {
            $issues[] = $matches[1];
        }

        $year = date('Y', strtotime($pr['created_at']));
        $dimNum = date($dim, strtotime($pr['created_at']));
        $num = $year . '-' . $dimNum;
        $stat[$num]['opened'][] = $pr['number'];

        if (isset($pr['closed_at'])) {
            $year = date('Y', strtotime($pr['closed_at']));
            $dimNum = date($dim, strtotime($pr['closed_at']));
            $num = $year . '-' . $dimNum;
            if ($pr['merged_at'] == null) {
                //rejected
                $stat[$num]['rejected'][] = $pr['number'];
            } else {
                //accepted
                $stat[$num]['accepted'][] = $pr['number'];
            }
        }
    }
    return $stat;
}


