<?php

// This file is generated by Composer
require_once 'vendor/autoload.php';

use Elasticsearch\ClientBuilder;

$stat = prstat();
krsort($stat);
echo '<table border="1">';
echo "<tr><th>Week</th><th>Opened</th><th>Accepted</th><th>Rejected</th>";
foreach ($stat as $week => $weekStat) {
    echo "<tr><td>" . $week . "</td>";
    echo "<td>";
    if (isset($weekStat['opened'])) {
        echo count($weekStat['opened']);
    } else {
        echo 0;
    }

    echo "</td><td>";
    if (array_key_exists('accepted', $weekStat)) {
        echo count($weekStat['accepted']);
    } else {
        echo 0;
    }
    echo  "</td><td>";
    if (isset($weekStat['rejected'])) {
        echo count($weekStat['rejected']);
    } else {
        echo 0;
    }
    echo "</td></tr>";
}
echo "</table>";

function prstat() {

    //$esClient = ClientBuilder::create()->build();

    $client = new \Github\Client();

    $token = "";
    if (!file_exists(".githubtoken")) {
        throw new Exception("Create file .githubtoken and put valid GitHub token there");
    } else {
        $token = file_get_contents(".githubtoken");
    }
    /** @var \Github\Api\PullRequest $pullRequests */
    $client->authenticate($token, null, \Github\Client::AUTH_HTTP_TOKEN);
    $pullRequests = $client->api('pull_requests');

    $page = 1;
    $prs = $pullRequests->all('magento', 'magento2',
        ['page' => $page]
    );
    while (count($prs) > 0) {
        foreach ($prs as $pr) {
// push to ES
//            $esClient->index([
//                'index' => 'get_pull_requests',
//                'type' => 'pull_request',
//                'id' => 'pr_id',
//                'body' => $pr
//            ]);

            $year = date('Y', strtotime($pr['created_at']));
            $weekNum = date('W', strtotime($pr['created_at']));
            $num = $year . '-' . $weekNum;
            $stat[$num]['opened'][] = $pr['number'];

        }
        $page++;
        $prs = $pullRequests->all('magento', 'magento2',
            ['page' => $page]
        );
    }


    $page = 1;
    $prs = $pullRequests->all('magento', 'magento2',
        ['state' => 'closed', 'page' => $page]
    );
    while (count($prs) > 0) {
        foreach ($prs as $pr) {
// push to ES
//            $esClient->index([
//                'index' => 'get_pull_requests',
//                'type' => 'pull_request',
//                //'id' => 'pr_id',
//                'body' => $pr
//            ]);

            $year = date('Y', strtotime($pr['created_at']));
            $weekNum = date('W', strtotime($pr['created_at']));
            $stat[$year . '-' . $weekNum]['opened'][] = $pr['number'];

            $year = date('Y', strtotime($pr['closed_at']));
            $weekNum = date('W', strtotime($pr['closed_at']));
            if ($pr['merged_at'] == null) {
                //rejected
                $stat[$year . '-' . $weekNum]['rejected'][] = $pr['number'];
            } else {
                //accepted
                $stat[$year . '-' . $weekNum]['accepted'][] = $pr['number'];
            }
        }
        $page++;
        $prs = $pullRequests->all('magento', 'magento2',
            ['state' => 'closed', 'page' => $page]
        );
    }

    return $stat;
}


